server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Reverse proxy lel API
    # Ay requete tabda b /api/ temchi lel Backend ClusterIP
    location /api/ {
        proxy_pass http://backend-service:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Websocket lel notifications
    location /ws-notifications {
        proxy_pass http://backend-service:8081;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }

    # Ken l'API mte3ek mafihech /api/ w t3adi direct / (mathalan /login), tnajem tzid location mte3ha houni
}
