spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: postgres
    password: Mahdi2001
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: piuayuie@gmail.com
    
    password: kttr ahwm xzpi snsc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
        expiration: 604800000

# URL mtaa el Predictive Agent (fi Kubernetes bch tjib men env variable PREDICTIVE_AGENT_URL)
predictive:
  agent:
    url: ${PREDICTIVE_AGENT_URL:http://localhost:8000}

# Frontend Base URL (Exposé via Ngrok)
app:
  frontend:
    url: ${FRONTEND_URL:https://thwarting-envision-overstuff.ngrok-free.dev}

